# Multiple secrets required by the OpenHands chart
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
stringData:
  jwt-secret: ENC[AES256_GCM,data:2od1Vj8ewqBlC02vA1bHjs2DysQvjJalkL9ojrW+IK4=,iv:ZDaeuRmFN+n+prP4EdoL/LpQlU7VIwZsZ8M6OPtYa7A=,tag:BRWs+pYU4HOp3604GAB0jw==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2NhTVhud0M4STJ1WFFH
        ODhRaFJzWVlBbnF4eVc4K3J1d0NZQWtLeTNVCjBHYzV6Y2ZBZDJEbVhhaUZwaVFX
        VVBZb0pERkdXVFBxZ3NUWFZ4Nk0xNkEKLS0tIFpINnVFKzlmWTFmTzNWSVNraWpz
        bkxkVlArbXVFOGZNK2xiTStlWTVGSWcKCSjebZ2m+0P6nLNpPPFyEcrkyoUCYR9S
        u2+JsyxW/wRMYrcRQ7PSwbtLScSJzsA1YqGhkzntNf62QhVCy3SIrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T09:31:56Z"
  mac: ENC[AES256_GCM,data:SH9QodwM2idsA788rz6cEy1VjaufFXHWc8fpBgsPbTWDxa3qmSjnXKNXsk+ci5td4AU9RUKEab9zavPn2eLm32aNogTAg2kt2uOlqJN45ttQiPGZC2jqqQaAMlJf1yfNkrkblD4hUX8+mn2qNPJP94xgFwHIm4bOvKFTvISIDXY=,iv:gCwYfAE/xJK+pIQW/tsed3W4JTC3cylD29juVPOJ8ck=,tag:zB4j1WpAemDuywjCwe9XcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: redis
stringData:
  redis-password: ENC[AES256_GCM,data:q3zvTlrmzTXQ29+vUeKUImiHXA4wL6cjIO/E,iv:Q3+nsK4JaOa9IGlJOh1GpIqgtlls7jIP0yT9KAjae2g=,tag:zy/GDk7SqH4lICc0IaI7Qw==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2NhTVhud0M4STJ1WFFH
        ODhRaFJzWVlBbnF4eVc4K3J1d0NZQWtLeTNVCjBHYzV6Y2ZBZDJEbVhhaUZwaVFX
        VVBZb0pERkdXVFBxZ3NUWFZ4Nk0xNkEKLS0tIFpINnVFKzlmWTFmTzNWSVNraWpz
        bkxkVlArbXVFOGZNK2xiTStlWTVGSWcKCSjebZ2m+0P6nLNpPPFyEcrkyoUCYR9S
        u2+JsyxW/wRMYrcRQ7PSwbtLScSJzsA1YqGhkzntNf62QhVCy3SIrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T09:31:56Z"
  mac: ENC[AES256_GCM,data:SH9QodwM2idsA788rz6cEy1VjaufFXHWc8fpBgsPbTWDxa3qmSjnXKNXsk+ci5td4AU9RUKEab9zavPn2eLm32aNogTAg2kt2uOlqJN45ttQiPGZC2jqqQaAMlJf1yfNkrkblD4hUX8+mn2qNPJP94xgFwHIm4bOvKFTvISIDXY=,iv:gCwYfAE/xJK+pIQW/tsed3W4JTC3cylD29juVPOJ8ck=,tag:zB4j1WpAemDuywjCwe9XcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
stringData:
  username: ENC[AES256_GCM,data:OwGy2P45WHQ=,iv:mhcklXGnIriXn2ispxZLpZepJ5fRmK+j38cwwpWPNzI=,tag:30auvciqjX0gysDjQDXomA==,type:str]
  password: ENC[AES256_GCM,data:OZOdgJ5ZmM0PWzXx7+xZOQV2lzg/U/afDRaRF0zq,iv:hcy/PONZfM41MxyBeGDtGlHutmWpLvjg6wBgTjUlBC0=,tag:0MKYt4M15HwjexZwG0AgkA==,type:str]
  postgres-password: ENC[AES256_GCM,data:a9F6AsU0jsy0lqtPz29vkK8n0d9hgDG3JgB9MqBY,iv:2e/Ai3FE17XySrYldm3Z6YZUvo0em2A4bV06fVdiKTY=,tag:aMZTVLTHjpRSIIXy7Ik8SA==,type:str]
  postgresql-password: ENC[AES256_GCM,data:qcc2OKgOzlL302Wp4Rv4A7eG2nPXXJ4ncO1A/dyc,iv:aB/wM21I40IBTD13TGNkyfDImiRDcPPlKx0w89XISmg=,tag:VncunWg4oOvI7CBEYzV+WQ==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2NhTVhud0M4STJ1WFFH
        ODhRaFJzWVlBbnF4eVc4K3J1d0NZQWtLeTNVCjBHYzV6Y2ZBZDJEbVhhaUZwaVFX
        VVBZb0pERkdXVFBxZ3NUWFZ4Nk0xNkEKLS0tIFpINnVFKzlmWTFmTzNWSVNraWpz
        bkxkVlArbXVFOGZNK2xiTStlWTVGSWcKCSjebZ2m+0P6nLNpPPFyEcrkyoUCYR9S
        u2+JsyxW/wRMYrcRQ7PSwbtLScSJzsA1YqGhkzntNf62QhVCy3SIrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T09:31:56Z"
  mac: ENC[AES256_GCM,data:SH9QodwM2idsA788rz6cEy1VjaufFXHWc8fpBgsPbTWDxa3qmSjnXKNXsk+ci5td4AU9RUKEab9zavPn2eLm32aNogTAg2kt2uOlqJN45ttQiPGZC2jqqQaAMlJf1yfNkrkblD4hUX8+mn2qNPJP94xgFwHIm4bOvKFTvISIDXY=,iv:gCwYfAE/xJK+pIQW/tsed3W4JTC3cylD29juVPOJ8ck=,tag:zB4j1WpAemDuywjCwe9XcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: lite-llm-api-key
stringData:
  lite-llm-api-key: ENC[AES256_GCM,data:Oy4jItFRhRsi1JpCottsDBnRqahkUtRJgzvekweT/Gc=,iv:O5HwVgnPVR8OEfZ9spvgE8l8k7WeY3u8dIqBHudKEgs=,tag:8m97oEJlN/fYqVVb120vSw==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2NhTVhud0M4STJ1WFFH
        ODhRaFJzWVlBbnF4eVc4K3J1d0NZQWtLeTNVCjBHYzV6Y2ZBZDJEbVhhaUZwaVFX
        VVBZb0pERkdXVFBxZ3NUWFZ4Nk0xNkEKLS0tIFpINnVFKzlmWTFmTzNWSVNraWpz
        bkxkVlArbXVFOGZNK2xiTStlWTVGSWcKCSjebZ2m+0P6nLNpPPFyEcrkyoUCYR9S
        u2+JsyxW/wRMYrcRQ7PSwbtLScSJzsA1YqGhkzntNf62QhVCy3SIrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T09:31:56Z"
  mac: ENC[AES256_GCM,data:SH9QodwM2idsA788rz6cEy1VjaufFXHWc8fpBgsPbTWDxa3qmSjnXKNXsk+ci5td4AU9RUKEab9zavPn2eLm32aNogTAg2kt2uOlqJN45ttQiPGZC2jqqQaAMlJf1yfNkrkblD4hUX8+mn2qNPJP94xgFwHIm4bOvKFTvISIDXY=,iv:gCwYfAE/xJK+pIQW/tsed3W4JTC3cylD29juVPOJ8ck=,tag:zB4j1WpAemDuywjCwe9XcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: sandbox-api-key
stringData:
  sandbox-api-key: ENC[AES256_GCM,data:k+cex+xdIe/SPfoDiXGULSX0bxlzp/z7/hviVKIswv8=,iv:yG/JSKJKZCSpPjFZILq9vnRQG8xLRIGGS7yFD7WqAGk=,tag:fEVXyCzOWxmAKJnWhkQGAg==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2NhTVhud0M4STJ1WFFH
        ODhRaFJzWVlBbnF4eVc4K3J1d0NZQWtLeTNVCjBHYzV6Y2ZBZDJEbVhhaUZwaVFX
        VVBZb0pERkdXVFBxZ3NUWFZ4Nk0xNkEKLS0tIFpINnVFKzlmWTFmTzNWSVNraWpz
        bkxkVlArbXVFOGZNK2xiTStlWTVGSWcKCSjebZ2m+0P6nLNpPPFyEcrkyoUCYR9S
        u2+JsyxW/wRMYrcRQ7PSwbtLScSJzsA1YqGhkzntNf62QhVCy3SIrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T09:31:56Z"
  mac: ENC[AES256_GCM,data:SH9QodwM2idsA788rz6cEy1VjaufFXHWc8fpBgsPbTWDxa3qmSjnXKNXsk+ci5td4AU9RUKEab9zavPn2eLm32aNogTAg2kt2uOlqJN45ttQiPGZC2jqqQaAMlJf1yfNkrkblD4hUX8+mn2qNPJP94xgFwHIm4bOvKFTvISIDXY=,iv:gCwYfAE/xJK+pIQW/tsed3W4JTC3cylD29juVPOJ8ck=,tag:zB4j1WpAemDuywjCwe9XcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: default-api-key
stringData:
  default-api-key: ENC[AES256_GCM,data:4Wbcpjh0fFbriOg0p0+CyHNjiKrBG2x+wgpRaFo3Nfk=,iv:0qr3TcdzPIxTzI9H6GZyjFJbgnUa9A95wi0KJXEM3eo=,tag:s2bIODcdJLexq6I0x1funA==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2NhTVhud0M4STJ1WFFH
        ODhRaFJzWVlBbnF4eVc4K3J1d0NZQWtLeTNVCjBHYzV6Y2ZBZDJEbVhhaUZwaVFX
        VVBZb0pERkdXVFBxZ3NUWFZ4Nk0xNkEKLS0tIFpINnVFKzlmWTFmTzNWSVNraWpz
        bkxkVlArbXVFOGZNK2xiTStlWTVGSWcKCSjebZ2m+0P6nLNpPPFyEcrkyoUCYR9S
        u2+JsyxW/wRMYrcRQ7PSwbtLScSJzsA1YqGhkzntNf62QhVCy3SIrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T09:31:56Z"
  mac: ENC[AES256_GCM,data:SH9QodwM2idsA788rz6cEy1VjaufFXHWc8fpBgsPbTWDxa3qmSjnXKNXsk+ci5td4AU9RUKEab9zavPn2eLm32aNogTAg2kt2uOlqJN45ttQiPGZC2jqqQaAMlJf1yfNkrkblD4hUX8+mn2qNPJP94xgFwHIm4bOvKFTvISIDXY=,iv:gCwYfAE/xJK+pIQW/tsed3W4JTC3cylD29juVPOJ8ck=,tag:zB4j1WpAemDuywjCwe9XcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-realm
stringData:
  realm-name: ENC[AES256_GCM,data:EW8reV16APkI,iv:GO0RIUJSAsGIkf5jmPhytkAOkVaj67HC743QLQXz4CA=,tag:OXw12/NBwLnRLqP/LEiFPA==,type:str]
  provider-name: ENC[AES256_GCM,data:Pb18BNs=,iv:djFRXNMi5hTEHzGK/X0GXzSAkq0LlvSQc58twVyWZ5w=,tag:buO9buYNkKw1TJEb01plAw==,type:str]
  server-url: ENC[AES256_GCM,data:RuQNobPEXwnJmDg2fFg0E94p0S4w9kEbw9Iu/f7s,iv:551zdBOJC9UAZBzsL5PPZku1bHCx+yYDjge/qjVB7mU=,tag:bSfKKcHViTgPRb9TBNo6nQ==,type:str]
  client-id: ENC[AES256_GCM,data:QgkwTuXNRTdU,iv:9ekR9q6iQ2N7AcZ5cDtBDaXolIy5FOgQyMD9MYl7H2E=,tag:96mAij2TBVXQDfkhHipMKg==,type:str]
  client-secret: ENC[AES256_GCM,data:inQX+GDXxSF/8xenwK4JR7SBmNQL7ZxbAq4/HyV6p9U=,iv:f72icF1/nOVlTquFA1l7mXFXaroe1MZk1bFcIabthjk=,tag:EbPBSVI4ZWLRVAMvbwSAaw==,type:str]
  smtp-password: ""
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2NhTVhud0M4STJ1WFFH
        ODhRaFJzWVlBbnF4eVc4K3J1d0NZQWtLeTNVCjBHYzV6Y2ZBZDJEbVhhaUZwaVFX
        VVBZb0pERkdXVFBxZ3NUWFZ4Nk0xNkEKLS0tIFpINnVFKzlmWTFmTzNWSVNraWpz
        bkxkVlArbXVFOGZNK2xiTStlWTVGSWcKCSjebZ2m+0P6nLNpPPFyEcrkyoUCYR9S
        u2+JsyxW/wRMYrcRQ7PSwbtLScSJzsA1YqGhkzntNf62QhVCy3SIrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T09:31:56Z"
  mac: ENC[AES256_GCM,data:SH9QodwM2idsA788rz6cEy1VjaufFXHWc8fpBgsPbTWDxa3qmSjnXKNXsk+ci5td4AU9RUKEab9zavPn2eLm32aNogTAg2kt2uOlqJN45ttQiPGZC2jqqQaAMlJf1yfNkrkblD4hUX8+mn2qNPJP94xgFwHIm4bOvKFTvISIDXY=,iv:gCwYfAE/xJK+pIQW/tsed3W4JTC3cylD29juVPOJ8ck=,tag:zB4j1WpAemDuywjCwe9XcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
stringData:
  admin-password: ENC[AES256_GCM,data:DbJdh23Ock9F4mqRrvep2f3NGDD6eyDhOssgou2qOS8=,iv:Cx3fBYY9mOC/dhYCmDK8NxU9iQ5fuQJYezo3CblDHeU=,tag:lSGdh4zaXo3AZLwoLCTM5w==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2NhTVhud0M4STJ1WFFH
        ODhRaFJzWVlBbnF4eVc4K3J1d0NZQWtLeTNVCjBHYzV6Y2ZBZDJEbVhhaUZwaVFX
        VVBZb0pERkdXVFBxZ3NUWFZ4Nk0xNkEKLS0tIFpINnVFKzlmWTFmTzNWSVNraWpz
        bkxkVlArbXVFOGZNK2xiTStlWTVGSWcKCSjebZ2m+0P6nLNpPPFyEcrkyoUCYR9S
        u2+JsyxW/wRMYrcRQ7PSwbtLScSJzsA1YqGhkzntNf62QhVCy3SIrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T09:31:56Z"
  mac: ENC[AES256_GCM,data:SH9QodwM2idsA788rz6cEy1VjaufFXHWc8fpBgsPbTWDxa3qmSjnXKNXsk+ci5td4AU9RUKEab9zavPn2eLm32aNogTAg2kt2uOlqJN45ttQiPGZC2jqqQaAMlJf1yfNkrkblD4hUX8+mn2qNPJP94xgFwHIm4bOvKFTvISIDXY=,iv:gCwYfAE/xJK+pIQW/tsed3W4JTC3cylD29juVPOJ8ck=,tag:zB4j1WpAemDuywjCwe9XcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: github-app
stringData:
  app-id: ""
  webhook-secret: ""
  client-id: ""
  client-secret: ""
  private-key: ""
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2NhTVhud0M4STJ1WFFH
        ODhRaFJzWVlBbnF4eVc4K3J1d0NZQWtLeTNVCjBHYzV6Y2ZBZDJEbVhhaUZwaVFX
        VVBZb0pERkdXVFBxZ3NUWFZ4Nk0xNkEKLS0tIFpINnVFKzlmWTFmTzNWSVNraWpz
        bkxkVlArbXVFOGZNK2xiTStlWTVGSWcKCSjebZ2m+0P6nLNpPPFyEcrkyoUCYR9S
        u2+JsyxW/wRMYrcRQ7PSwbtLScSJzsA1YqGhkzntNf62QhVCy3SIrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T09:31:56Z"
  mac: ENC[AES256_GCM,data:SH9QodwM2idsA788rz6cEy1VjaufFXHWc8fpBgsPbTWDxa3qmSjnXKNXsk+ci5td4AU9RUKEab9zavPn2eLm32aNogTAg2kt2uOlqJN45ttQiPGZC2jqqQaAMlJf1yfNkrkblD4hUX8+mn2qNPJP94xgFwHIm4bOvKFTvISIDXY=,iv:gCwYfAE/xJK+pIQW/tsed3W4JTC3cylD29juVPOJ8ck=,tag:zB4j1WpAemDuywjCwe9XcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-app
stringData:
  client-id: ""
  client-secret: ""
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2NhTVhud0M4STJ1WFFH
        ODhRaFJzWVlBbnF4eVc4K3J1d0NZQWtLeTNVCjBHYzV6Y2ZBZDJEbVhhaUZwaVFX
        VVBZb0pERkdXVFBxZ3NUWFZ4Nk0xNkEKLS0tIFpINnVFKzlmWTFmTzNWSVNraWpz
        bkxkVlArbXVFOGZNK2xiTStlWTVGSWcKCSjebZ2m+0P6nLNpPPFyEcrkyoUCYR9S
        u2+JsyxW/wRMYrcRQ7PSwbtLScSJzsA1YqGhkzntNf62QhVCy3SIrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T09:31:56Z"
  mac: ENC[AES256_GCM,data:SH9QodwM2idsA788rz6cEy1VjaufFXHWc8fpBgsPbTWDxa3qmSjnXKNXsk+ci5td4AU9RUKEab9zavPn2eLm32aNogTAg2kt2uOlqJN45ttQiPGZC2jqqQaAMlJf1yfNkrkblD4hUX8+mn2qNPJP94xgFwHIm4bOvKFTvISIDXY=,iv:gCwYfAE/xJK+pIQW/tsed3W4JTC3cylD29juVPOJ8ck=,tag:zB4j1WpAemDuywjCwe9XcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-password
stringData:
  password: ENC[AES256_GCM,data:fCv8b6dSS9ugG0WLFd7wQav1BCYSy1cfvNoKo6oXjWI=,iv:B9W4wYEnhhltXxutk6119O7Iz7GvNvfH8BDaZEHEXWg=,tag:pW0PHIcS3mSQ5xk7TDTgAQ==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2NhTVhud0M4STJ1WFFH
        ODhRaFJzWVlBbnF4eVc4K3J1d0NZQWtLeTNVCjBHYzV6Y2ZBZDJEbVhhaUZwaVFX
        VVBZb0pERkdXVFBxZ3NUWFZ4Nk0xNkEKLS0tIFpINnVFKzlmWTFmTzNWSVNraWpz
        bkxkVlArbXVFOGZNK2xiTStlWTVGSWcKCSjebZ2m+0P6nLNpPPFyEcrkyoUCYR9S
        u2+JsyxW/wRMYrcRQ7PSwbtLScSJzsA1YqGhkzntNf62QhVCy3SIrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T09:31:56Z"
  mac: ENC[AES256_GCM,data:SH9QodwM2idsA788rz6cEy1VjaufFXHWc8fpBgsPbTWDxa3qmSjnXKNXsk+ci5td4AU9RUKEab9zavPn2eLm32aNogTAg2kt2uOlqJN45ttQiPGZC2jqqQaAMlJf1yfNkrkblD4hUX8+mn2qNPJP94xgFwHIm4bOvKFTvISIDXY=,iv:gCwYfAE/xJK+pIQW/tsed3W4JTC3cylD29juVPOJ8ck=,tag:zB4j1WpAemDuywjCwe9XcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-salt
stringData:
  salt: ENC[AES256_GCM,data:IznetdR8VOUKljps/IkRVcV9DNx/SiXEVj5DF1FB0uQ=,iv:/Vsyrcm9T+UsOjUrfEtU2Gvp6Nakv/iqbUssnTDJp7U=,tag:2pb3VceszSqDIbCqxEXp0A==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2NhTVhud0M4STJ1WFFH
        ODhRaFJzWVlBbnF4eVc4K3J1d0NZQWtLeTNVCjBHYzV6Y2ZBZDJEbVhhaUZwaVFX
        VVBZb0pERkdXVFBxZ3NUWFZ4Nk0xNkEKLS0tIFpINnVFKzlmWTFmTzNWSVNraWpz
        bkxkVlArbXVFOGZNK2xiTStlWTVGSWcKCSjebZ2m+0P6nLNpPPFyEcrkyoUCYR9S
        u2+JsyxW/wRMYrcRQ7PSwbtLScSJzsA1YqGhkzntNf62QhVCy3SIrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T09:31:56Z"
  mac: ENC[AES256_GCM,data:SH9QodwM2idsA788rz6cEy1VjaufFXHWc8fpBgsPbTWDxa3qmSjnXKNXsk+ci5td4AU9RUKEab9zavPn2eLm32aNogTAg2kt2uOlqJN45ttQiPGZC2jqqQaAMlJf1yfNkrkblD4hUX8+mn2qNPJP94xgFwHIm4bOvKFTvISIDXY=,iv:gCwYfAE/xJK+pIQW/tsed3W4JTC3cylD29juVPOJ8ck=,tag:zB4j1WpAemDuywjCwe9XcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-nextauth
stringData:
  nextauth-secret: ENC[AES256_GCM,data:IeKfcBmC/gG6jhrxSkC/mugSuT+7GG9XQKhEKTFbSE0=,iv:Hc0snjZt8cjUiU2hC0HvlDafmTERAsI23lE/aPGVM38=,tag:MsEUHlU/xProndaIPdgkaA==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2NhTVhud0M4STJ1WFFH
        ODhRaFJzWVlBbnF4eVc4K3J1d0NZQWtLeTNVCjBHYzV6Y2ZBZDJEbVhhaUZwaVFX
        VVBZb0pERkdXVFBxZ3NUWFZ4Nk0xNkEKLS0tIFpINnVFKzlmWTFmTzNWSVNraWpz
        bkxkVlArbXVFOGZNK2xiTStlWTVGSWcKCSjebZ2m+0P6nLNpPPFyEcrkyoUCYR9S
        u2+JsyxW/wRMYrcRQ7PSwbtLScSJzsA1YqGhkzntNf62QhVCy3SIrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T09:31:56Z"
  mac: ENC[AES256_GCM,data:SH9QodwM2idsA788rz6cEy1VjaufFXHWc8fpBgsPbTWDxa3qmSjnXKNXsk+ci5td4AU9RUKEab9zavPn2eLm32aNogTAg2kt2uOlqJN45ttQiPGZC2jqqQaAMlJf1yfNkrkblD4hUX8+mn2qNPJP94xgFwHIm4bOvKFTvISIDXY=,iv:gCwYfAE/xJK+pIQW/tsed3W4JTC3cylD29juVPOJ8ck=,tag:zB4j1WpAemDuywjCwe9XcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: litellm-env-secrets
stringData:
  LLM_API_KEY: ENC[AES256_GCM,data:CPGzm8o=,iv:Da9S0j8eTrvy8LfrJf+3Akd+cH7cZCZEp0FmS4DiJ34=,tag:d+/SR3ugvOszkp5tZRJtgw==,type:str]
  LLM_MODEL: ENC[AES256_GCM,data:/Ori3IPFtqA66p0Pwlp2ODXJxyTj54HIhxqAurgw6h8ISRzt31u0D2E=,iv:1x/7b1HZeN80bmknASAkvWUrnkK4dGydZI1tUrvPdio=,tag:9GTUC8ztuVRWPOaxmvKG4g==,type:str]
  LLM_BASE_URL: ENC[AES256_GCM,data:8JJiBYW968axJpe3v2wRXPp3Eq5LAu1t3+Ee,iv:zvo+nULOcxZku6IUhRnApuq/xdBtRKQPSgro7pvS5NY=,tag:MMIVjqB8m5x1Db2Q+ZKEJw==,type:str]
  LLM_TIMEOUT: ENC[AES256_GCM,data:luPlpA==,iv:Oq0paD2nAAxh193UrxE2/XY3ySMFkKNjgvAgh+j5agE=,tag:uDLjEeblE+J4LsI8GtnU/A==,type:str]
  LLM_MAX_OUTPUT_TOKENS: ENC[AES256_GCM,data:0DCMWBI=,iv:uazLC6WCIaEF9eqBre581LwYjZQI4yjei3AsGO4WnvQ=,tag:MhAO2jG1MaNWnUs8mnkO2w==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2NhTVhud0M4STJ1WFFH
        ODhRaFJzWVlBbnF4eVc4K3J1d0NZQWtLeTNVCjBHYzV6Y2ZBZDJEbVhhaUZwaVFX
        VVBZb0pERkdXVFBxZ3NUWFZ4Nk0xNkEKLS0tIFpINnVFKzlmWTFmTzNWSVNraWpz
        bkxkVlArbXVFOGZNK2xiTStlWTVGSWcKCSjebZ2m+0P6nLNpPPFyEcrkyoUCYR9S
        u2+JsyxW/wRMYrcRQ7PSwbtLScSJzsA1YqGhkzntNf62QhVCy3SIrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T09:31:56Z"
  mac: ENC[AES256_GCM,data:SH9QodwM2idsA788rz6cEy1VjaufFXHWc8fpBgsPbTWDxa3qmSjnXKNXsk+ci5td4AU9RUKEab9zavPn2eLm32aNogTAg2kt2uOlqJN45ttQiPGZC2jqqQaAMlJf1yfNkrkblD4hUX8+mn2qNPJP94xgFwHIm4bOvKFTvISIDXY=,iv:gCwYfAE/xJK+pIQW/tsed3W4JTC3cylD29juVPOJ8ck=,tag:zB4j1WpAemDuywjCwe9XcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  # ‚áê must match imagePullSecrets entry
  name: ghcr-login-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:ZOdFSODmx6nH9X6vsZlEm7UQKxlJSGNwMfTSXXa2dZXlckLQb5+RZncjLI8x/BaH9bCg0WTmgaxumHAXgPwSCHvxn/ADfB4Oy8V3gLk3WKbR8QtWwrmij0pLL9X3btG0ezW/COVEB9lLcfcrQWb0GlkewvgKuFCwMKxHuvwU0e2bbzSp2g6bNLVab4KsFeieWXy1IwqoBB72ozMzzptTLD/IqgneN4dYl4ck1bkJoMdbMMXtTuo/8frqJrl8ijN0ZuDmyPPaHWc7aUQvaG2fbT/Slz+gEACvJucPbe9nMr9TaySEKN0E/IjIJ7NdWqByzpH3lCYwmnE=,iv:MmgsGK6R/goPMjNvPHaXYRGoJluilTASs/efWak/WUI=,tag:uCAZwmN/FnyBEwFRkhLg5g==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2NhTVhud0M4STJ1WFFH
        ODhRaFJzWVlBbnF4eVc4K3J1d0NZQWtLeTNVCjBHYzV6Y2ZBZDJEbVhhaUZwaVFX
        VVBZb0pERkdXVFBxZ3NUWFZ4Nk0xNkEKLS0tIFpINnVFKzlmWTFmTzNWSVNraWpz
        bkxkVlArbXVFOGZNK2xiTStlWTVGSWcKCSjebZ2m+0P6nLNpPPFyEcrkyoUCYR9S
        u2+JsyxW/wRMYrcRQ7PSwbtLScSJzsA1YqGhkzntNf62QhVCy3SIrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T09:31:56Z"
  mac: ENC[AES256_GCM,data:SH9QodwM2idsA788rz6cEy1VjaufFXHWc8fpBgsPbTWDxa3qmSjnXKNXsk+ci5td4AU9RUKEab9zavPn2eLm32aNogTAg2kt2uOlqJN45ttQiPGZC2jqqQaAMlJf1yfNkrkblD4hUX8+mn2qNPJP94xgFwHIm4bOvKFTvISIDXY=,iv:gCwYfAE/xJK+pIQW/tsed3W4JTC3cylD29juVPOJ8ck=,tag:zB4j1WpAemDuywjCwe9XcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
