# Multiple secrets required by the OpenHands chart
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
stringData:
  jwt-secret: ENC[AES256_GCM,data:4EA3NzH5mV+K4BOYKa4fZK28lW5gvGqxYtGE9Dl4Ooo=,iv:QQ+vLF+PzKbCUzdK34mQyBcQAw1o2+RaxkDg4Vl4D24=,tag:qzeML8fRs/lZTdG3u7FTiA==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGdoQ2J1QTFWUmE3Q0R5
        WXI5ZEhISHZkL1V6NXN1TnhYZG93bXNrS1VnCmx3eXpNUVdKajdTeHkwdGJXeGhN
        YnRFd1RMSXlSeWg5R0pCWUtGUDBoeFEKLS0tIFRGcnVTR2Y2VkdWMjdQYXAwbDVv
        ZTNPZmRUem9xYWFvcjlJL1owRmw1Z0kKdmz28FtkTsaD2p8uiwkXdNqmZSJXJcmW
        lpGowXY6aRVRpY/MGT0S5eLdCN2QGAe+pMV+XTbDt0hRvdZMcLHdhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T10:14:55Z"
  mac: ENC[AES256_GCM,data:AgriSc9pyc8Ue+Jz69S7P6DRrM3U10oVXO9+ap+IxjUeTe0RIiYMudjs2btHVxSC85H5IaO875IM7S0LiIgZmBN6w/GOFXK/NoERvUADKnd1a4/ParfAfkle9Jg4d6hDQ4LC59ijzZbiIxerZl2Iptpd1ydoK1apb0R6u9A7qf4=,iv:XOp+rhihpELSqPsGB57t7p6H3uXTJR5KJaerGpfzi9Q=,tag:iGZCFlBYdJXLnF99e4gp1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: redis
stringData:
  redis-password: ENC[AES256_GCM,data:qUF/WWKNQUAsKeeenxEGDxQHqSODVnuKiOqY,iv:u8J0JKhlz7YlghnBmRIg+8IOE0oqE4LdmeqQf5Ng2CQ=,tag:AWVooNYYr9LB4YImy9BM8Q==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGdoQ2J1QTFWUmE3Q0R5
        WXI5ZEhISHZkL1V6NXN1TnhYZG93bXNrS1VnCmx3eXpNUVdKajdTeHkwdGJXeGhN
        YnRFd1RMSXlSeWg5R0pCWUtGUDBoeFEKLS0tIFRGcnVTR2Y2VkdWMjdQYXAwbDVv
        ZTNPZmRUem9xYWFvcjlJL1owRmw1Z0kKdmz28FtkTsaD2p8uiwkXdNqmZSJXJcmW
        lpGowXY6aRVRpY/MGT0S5eLdCN2QGAe+pMV+XTbDt0hRvdZMcLHdhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T10:14:55Z"
  mac: ENC[AES256_GCM,data:AgriSc9pyc8Ue+Jz69S7P6DRrM3U10oVXO9+ap+IxjUeTe0RIiYMudjs2btHVxSC85H5IaO875IM7S0LiIgZmBN6w/GOFXK/NoERvUADKnd1a4/ParfAfkle9Jg4d6hDQ4LC59ijzZbiIxerZl2Iptpd1ydoK1apb0R6u9A7qf4=,iv:XOp+rhihpELSqPsGB57t7p6H3uXTJR5KJaerGpfzi9Q=,tag:iGZCFlBYdJXLnF99e4gp1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
stringData:
  username: ENC[AES256_GCM,data:kGaPj6aLf1c=,iv:mhb04DJQQO+uiMEvD9tl1yIKinX2ziGsj3FV9ebJMy8=,tag:XQdwKvbj1TFNtCrzpH7APg==,type:str]
  password: ENC[AES256_GCM,data:DuFghBHCieMykPz61djBnOjtFbf2BZSOp2h22l1M,iv:6P6CfraU+fMKKEunVjC2AUMQVaKyQ9S9qZ7YJyRIgqY=,tag:beNpnvP2dp+RJvFze2RMXw==,type:str]
  postgres-password: ENC[AES256_GCM,data:0RSkVmSFn9dygp6nSaNyjWxj5MvVj8woG2EkyVhm,iv:/zXkdVRejUx0DARwbcwi1Av2MjsF9S2i1eO+F49BUwI=,tag:7kRlNSDYWn1BAg1bw+Gz0g==,type:str]
  postgresql-password: ENC[AES256_GCM,data:0lQwlA4Q6SvsLP0ANsdSnf84b3fgLco4sMmaC4rV,iv:AkiZXSUcx6p4s1bYsAoadBraKKBHWBuGo3ipR2euP+A=,tag:6cOpemhYhcFIm0OdV9cEBg==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGdoQ2J1QTFWUmE3Q0R5
        WXI5ZEhISHZkL1V6NXN1TnhYZG93bXNrS1VnCmx3eXpNUVdKajdTeHkwdGJXeGhN
        YnRFd1RMSXlSeWg5R0pCWUtGUDBoeFEKLS0tIFRGcnVTR2Y2VkdWMjdQYXAwbDVv
        ZTNPZmRUem9xYWFvcjlJL1owRmw1Z0kKdmz28FtkTsaD2p8uiwkXdNqmZSJXJcmW
        lpGowXY6aRVRpY/MGT0S5eLdCN2QGAe+pMV+XTbDt0hRvdZMcLHdhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T10:14:55Z"
  mac: ENC[AES256_GCM,data:AgriSc9pyc8Ue+Jz69S7P6DRrM3U10oVXO9+ap+IxjUeTe0RIiYMudjs2btHVxSC85H5IaO875IM7S0LiIgZmBN6w/GOFXK/NoERvUADKnd1a4/ParfAfkle9Jg4d6hDQ4LC59ijzZbiIxerZl2Iptpd1ydoK1apb0R6u9A7qf4=,iv:XOp+rhihpELSqPsGB57t7p6H3uXTJR5KJaerGpfzi9Q=,tag:iGZCFlBYdJXLnF99e4gp1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: lite-llm-api-key
stringData:
  lite-llm-api-key: ENC[AES256_GCM,data:j6e8HozuOSICblKxgw53oGkjSVA5h0iU0jdOsaqeXdk=,iv:gmtn2lUKeGRph34VoZdixKmT4DN5d/LGh0WrOv9i1tA=,tag:3JNSy06SyIk8C/xBI3c0NQ==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGdoQ2J1QTFWUmE3Q0R5
        WXI5ZEhISHZkL1V6NXN1TnhYZG93bXNrS1VnCmx3eXpNUVdKajdTeHkwdGJXeGhN
        YnRFd1RMSXlSeWg5R0pCWUtGUDBoeFEKLS0tIFRGcnVTR2Y2VkdWMjdQYXAwbDVv
        ZTNPZmRUem9xYWFvcjlJL1owRmw1Z0kKdmz28FtkTsaD2p8uiwkXdNqmZSJXJcmW
        lpGowXY6aRVRpY/MGT0S5eLdCN2QGAe+pMV+XTbDt0hRvdZMcLHdhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T10:14:55Z"
  mac: ENC[AES256_GCM,data:AgriSc9pyc8Ue+Jz69S7P6DRrM3U10oVXO9+ap+IxjUeTe0RIiYMudjs2btHVxSC85H5IaO875IM7S0LiIgZmBN6w/GOFXK/NoERvUADKnd1a4/ParfAfkle9Jg4d6hDQ4LC59ijzZbiIxerZl2Iptpd1ydoK1apb0R6u9A7qf4=,iv:XOp+rhihpELSqPsGB57t7p6H3uXTJR5KJaerGpfzi9Q=,tag:iGZCFlBYdJXLnF99e4gp1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: sandbox-api-key
stringData:
  sandbox-api-key: ENC[AES256_GCM,data:Snbhw5Dpt7ofrRo8Jz4Y7DvRC7c2fx7tNyWM5JFyODk=,iv:jm06mLPpOP6r+49KRNr/CTZjqSN97YDaYqkHQzLyBUU=,tag:nQoYyrsgQt8Nb4gmlJ30DQ==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGdoQ2J1QTFWUmE3Q0R5
        WXI5ZEhISHZkL1V6NXN1TnhYZG93bXNrS1VnCmx3eXpNUVdKajdTeHkwdGJXeGhN
        YnRFd1RMSXlSeWg5R0pCWUtGUDBoeFEKLS0tIFRGcnVTR2Y2VkdWMjdQYXAwbDVv
        ZTNPZmRUem9xYWFvcjlJL1owRmw1Z0kKdmz28FtkTsaD2p8uiwkXdNqmZSJXJcmW
        lpGowXY6aRVRpY/MGT0S5eLdCN2QGAe+pMV+XTbDt0hRvdZMcLHdhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T10:14:55Z"
  mac: ENC[AES256_GCM,data:AgriSc9pyc8Ue+Jz69S7P6DRrM3U10oVXO9+ap+IxjUeTe0RIiYMudjs2btHVxSC85H5IaO875IM7S0LiIgZmBN6w/GOFXK/NoERvUADKnd1a4/ParfAfkle9Jg4d6hDQ4LC59ijzZbiIxerZl2Iptpd1ydoK1apb0R6u9A7qf4=,iv:XOp+rhihpELSqPsGB57t7p6H3uXTJR5KJaerGpfzi9Q=,tag:iGZCFlBYdJXLnF99e4gp1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: default-api-key
stringData:
  default-api-key: ENC[AES256_GCM,data:zCCZ3tUPv66i9WIhn1q5gbiNX8Kw5XKfxuHcwZjnHGM=,iv:0cY+Jo4MkpHum5QVOOTQSFrNYG3ShPk1x563SjMZ0R8=,tag:eShP+SL8dQZy/wEcHkeBXQ==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGdoQ2J1QTFWUmE3Q0R5
        WXI5ZEhISHZkL1V6NXN1TnhYZG93bXNrS1VnCmx3eXpNUVdKajdTeHkwdGJXeGhN
        YnRFd1RMSXlSeWg5R0pCWUtGUDBoeFEKLS0tIFRGcnVTR2Y2VkdWMjdQYXAwbDVv
        ZTNPZmRUem9xYWFvcjlJL1owRmw1Z0kKdmz28FtkTsaD2p8uiwkXdNqmZSJXJcmW
        lpGowXY6aRVRpY/MGT0S5eLdCN2QGAe+pMV+XTbDt0hRvdZMcLHdhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T10:14:55Z"
  mac: ENC[AES256_GCM,data:AgriSc9pyc8Ue+Jz69S7P6DRrM3U10oVXO9+ap+IxjUeTe0RIiYMudjs2btHVxSC85H5IaO875IM7S0LiIgZmBN6w/GOFXK/NoERvUADKnd1a4/ParfAfkle9Jg4d6hDQ4LC59ijzZbiIxerZl2Iptpd1ydoK1apb0R6u9A7qf4=,iv:XOp+rhihpELSqPsGB57t7p6H3uXTJR5KJaerGpfzi9Q=,tag:iGZCFlBYdJXLnF99e4gp1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-realm
stringData:
  realm-name: ENC[AES256_GCM,data:QbXCcd/ZbBYg,iv:4/g+wjaYE6TJawcqWyLwyUqxxpqSEJ22wBylCOa9bR0=,tag:q3/fyYutGUTDVhmy7kLCtw==,type:str]
  provider-name: ENC[AES256_GCM,data:47a7Ouc=,iv:NUQneZ2JxgpgNhFrJAMUEcWxJVhm1Klnq7VoyzRliK4=,tag:zlInA5iiuzLfqeP79C9Qtw==,type:str]
  server-url: ENC[AES256_GCM,data:yMKXVpZ8rtI4TFCpcx5XXiQITA61BW+8OV/xxz63,iv:brRDMRzqOTeFb9Cp/DG7shbQ8kSRxayQLH3ROcZTTVQ=,tag:q6OgaN4CpPkYLbKnqQJVDg==,type:str]
  client-id: ENC[AES256_GCM,data:yomazZWPhZ3V,iv:pc+e+Tlo9mId61oTS3RqJ189xP7mDHV/drYB9xMv/lA=,tag:T2urAS9mIi/Vu+oAqmm5jg==,type:str]
  client-secret: ENC[AES256_GCM,data:p8lYSsOe/fzvPH7UEKcaOInK2v/a8w+5GpKq7Fgb1M4=,iv:TSf3b/lmKgvzAu6ByHAxccliDz5gj+VgGOOOvqlLaxo=,tag:97Fay9BfnBEdIgGgHF7W2A==,type:str]
  smtp-password: ""
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGdoQ2J1QTFWUmE3Q0R5
        WXI5ZEhISHZkL1V6NXN1TnhYZG93bXNrS1VnCmx3eXpNUVdKajdTeHkwdGJXeGhN
        YnRFd1RMSXlSeWg5R0pCWUtGUDBoeFEKLS0tIFRGcnVTR2Y2VkdWMjdQYXAwbDVv
        ZTNPZmRUem9xYWFvcjlJL1owRmw1Z0kKdmz28FtkTsaD2p8uiwkXdNqmZSJXJcmW
        lpGowXY6aRVRpY/MGT0S5eLdCN2QGAe+pMV+XTbDt0hRvdZMcLHdhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T10:14:55Z"
  mac: ENC[AES256_GCM,data:AgriSc9pyc8Ue+Jz69S7P6DRrM3U10oVXO9+ap+IxjUeTe0RIiYMudjs2btHVxSC85H5IaO875IM7S0LiIgZmBN6w/GOFXK/NoERvUADKnd1a4/ParfAfkle9Jg4d6hDQ4LC59ijzZbiIxerZl2Iptpd1ydoK1apb0R6u9A7qf4=,iv:XOp+rhihpELSqPsGB57t7p6H3uXTJR5KJaerGpfzi9Q=,tag:iGZCFlBYdJXLnF99e4gp1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
stringData:
  admin-password: ENC[AES256_GCM,data:Ts0shwJUePUWjT/IxT6I7fMezzkUXemXgYXc0kQRMM0=,iv:olrwErgTe17aMee+xFt0/vCV6PkXhPoKgdEHBhWn2Ok=,tag:VSqw9+/e21U3kBXWf/lgJw==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGdoQ2J1QTFWUmE3Q0R5
        WXI5ZEhISHZkL1V6NXN1TnhYZG93bXNrS1VnCmx3eXpNUVdKajdTeHkwdGJXeGhN
        YnRFd1RMSXlSeWg5R0pCWUtGUDBoeFEKLS0tIFRGcnVTR2Y2VkdWMjdQYXAwbDVv
        ZTNPZmRUem9xYWFvcjlJL1owRmw1Z0kKdmz28FtkTsaD2p8uiwkXdNqmZSJXJcmW
        lpGowXY6aRVRpY/MGT0S5eLdCN2QGAe+pMV+XTbDt0hRvdZMcLHdhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T10:14:55Z"
  mac: ENC[AES256_GCM,data:AgriSc9pyc8Ue+Jz69S7P6DRrM3U10oVXO9+ap+IxjUeTe0RIiYMudjs2btHVxSC85H5IaO875IM7S0LiIgZmBN6w/GOFXK/NoERvUADKnd1a4/ParfAfkle9Jg4d6hDQ4LC59ijzZbiIxerZl2Iptpd1ydoK1apb0R6u9A7qf4=,iv:XOp+rhihpELSqPsGB57t7p6H3uXTJR5KJaerGpfzi9Q=,tag:iGZCFlBYdJXLnF99e4gp1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: github-app
stringData:
  app-id: ""
  webhook-secret: ""
  client-id: ""
  client-secret: ""
  private-key: ""
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGdoQ2J1QTFWUmE3Q0R5
        WXI5ZEhISHZkL1V6NXN1TnhYZG93bXNrS1VnCmx3eXpNUVdKajdTeHkwdGJXeGhN
        YnRFd1RMSXlSeWg5R0pCWUtGUDBoeFEKLS0tIFRGcnVTR2Y2VkdWMjdQYXAwbDVv
        ZTNPZmRUem9xYWFvcjlJL1owRmw1Z0kKdmz28FtkTsaD2p8uiwkXdNqmZSJXJcmW
        lpGowXY6aRVRpY/MGT0S5eLdCN2QGAe+pMV+XTbDt0hRvdZMcLHdhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T10:14:55Z"
  mac: ENC[AES256_GCM,data:AgriSc9pyc8Ue+Jz69S7P6DRrM3U10oVXO9+ap+IxjUeTe0RIiYMudjs2btHVxSC85H5IaO875IM7S0LiIgZmBN6w/GOFXK/NoERvUADKnd1a4/ParfAfkle9Jg4d6hDQ4LC59ijzZbiIxerZl2Iptpd1ydoK1apb0R6u9A7qf4=,iv:XOp+rhihpELSqPsGB57t7p6H3uXTJR5KJaerGpfzi9Q=,tag:iGZCFlBYdJXLnF99e4gp1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-app
stringData:
  client-id: ""
  client-secret: ""
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGdoQ2J1QTFWUmE3Q0R5
        WXI5ZEhISHZkL1V6NXN1TnhYZG93bXNrS1VnCmx3eXpNUVdKajdTeHkwdGJXeGhN
        YnRFd1RMSXlSeWg5R0pCWUtGUDBoeFEKLS0tIFRGcnVTR2Y2VkdWMjdQYXAwbDVv
        ZTNPZmRUem9xYWFvcjlJL1owRmw1Z0kKdmz28FtkTsaD2p8uiwkXdNqmZSJXJcmW
        lpGowXY6aRVRpY/MGT0S5eLdCN2QGAe+pMV+XTbDt0hRvdZMcLHdhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T10:14:55Z"
  mac: ENC[AES256_GCM,data:AgriSc9pyc8Ue+Jz69S7P6DRrM3U10oVXO9+ap+IxjUeTe0RIiYMudjs2btHVxSC85H5IaO875IM7S0LiIgZmBN6w/GOFXK/NoERvUADKnd1a4/ParfAfkle9Jg4d6hDQ4LC59ijzZbiIxerZl2Iptpd1ydoK1apb0R6u9A7qf4=,iv:XOp+rhihpELSqPsGB57t7p6H3uXTJR5KJaerGpfzi9Q=,tag:iGZCFlBYdJXLnF99e4gp1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-password
stringData:
  password: ENC[AES256_GCM,data:WAC4FMbpJJq5miKdcQ8+3F3TtJU2dWP+Z8tW5MmzsIk=,iv:Yz5z/xRMNB0ErVTiPvMpOWyhwisdixEdDmsQvkn8/xg=,tag:QB0ZeXRwTa5rv1jnTQ6RSg==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGdoQ2J1QTFWUmE3Q0R5
        WXI5ZEhISHZkL1V6NXN1TnhYZG93bXNrS1VnCmx3eXpNUVdKajdTeHkwdGJXeGhN
        YnRFd1RMSXlSeWg5R0pCWUtGUDBoeFEKLS0tIFRGcnVTR2Y2VkdWMjdQYXAwbDVv
        ZTNPZmRUem9xYWFvcjlJL1owRmw1Z0kKdmz28FtkTsaD2p8uiwkXdNqmZSJXJcmW
        lpGowXY6aRVRpY/MGT0S5eLdCN2QGAe+pMV+XTbDt0hRvdZMcLHdhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T10:14:55Z"
  mac: ENC[AES256_GCM,data:AgriSc9pyc8Ue+Jz69S7P6DRrM3U10oVXO9+ap+IxjUeTe0RIiYMudjs2btHVxSC85H5IaO875IM7S0LiIgZmBN6w/GOFXK/NoERvUADKnd1a4/ParfAfkle9Jg4d6hDQ4LC59ijzZbiIxerZl2Iptpd1ydoK1apb0R6u9A7qf4=,iv:XOp+rhihpELSqPsGB57t7p6H3uXTJR5KJaerGpfzi9Q=,tag:iGZCFlBYdJXLnF99e4gp1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-salt
stringData:
  salt: ENC[AES256_GCM,data:4qaRNn0MV48ggmzBiol7xjO6DjF4h3cREWVQw17t0yk=,iv:dY1wb3B2GEnxGXu/8ekCDx7738UEKIl867MgDz2Sml8=,tag:nfmvxZcjJvepXkKkPtRdnw==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGdoQ2J1QTFWUmE3Q0R5
        WXI5ZEhISHZkL1V6NXN1TnhYZG93bXNrS1VnCmx3eXpNUVdKajdTeHkwdGJXeGhN
        YnRFd1RMSXlSeWg5R0pCWUtGUDBoeFEKLS0tIFRGcnVTR2Y2VkdWMjdQYXAwbDVv
        ZTNPZmRUem9xYWFvcjlJL1owRmw1Z0kKdmz28FtkTsaD2p8uiwkXdNqmZSJXJcmW
        lpGowXY6aRVRpY/MGT0S5eLdCN2QGAe+pMV+XTbDt0hRvdZMcLHdhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T10:14:55Z"
  mac: ENC[AES256_GCM,data:AgriSc9pyc8Ue+Jz69S7P6DRrM3U10oVXO9+ap+IxjUeTe0RIiYMudjs2btHVxSC85H5IaO875IM7S0LiIgZmBN6w/GOFXK/NoERvUADKnd1a4/ParfAfkle9Jg4d6hDQ4LC59ijzZbiIxerZl2Iptpd1ydoK1apb0R6u9A7qf4=,iv:XOp+rhihpELSqPsGB57t7p6H3uXTJR5KJaerGpfzi9Q=,tag:iGZCFlBYdJXLnF99e4gp1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-nextauth
stringData:
  nextauth-secret: ENC[AES256_GCM,data:0eb72eMtRSbvbX1xlWdj3BaJ6GaTkhAaLmhadkBx7+s=,iv:V98hrV60evGCJFLlo0izuKrTqWN+VlD2jTkRkhWbG08=,tag:ZWjkzacYyxZxASz8cVW0+g==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGdoQ2J1QTFWUmE3Q0R5
        WXI5ZEhISHZkL1V6NXN1TnhYZG93bXNrS1VnCmx3eXpNUVdKajdTeHkwdGJXeGhN
        YnRFd1RMSXlSeWg5R0pCWUtGUDBoeFEKLS0tIFRGcnVTR2Y2VkdWMjdQYXAwbDVv
        ZTNPZmRUem9xYWFvcjlJL1owRmw1Z0kKdmz28FtkTsaD2p8uiwkXdNqmZSJXJcmW
        lpGowXY6aRVRpY/MGT0S5eLdCN2QGAe+pMV+XTbDt0hRvdZMcLHdhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T10:14:55Z"
  mac: ENC[AES256_GCM,data:AgriSc9pyc8Ue+Jz69S7P6DRrM3U10oVXO9+ap+IxjUeTe0RIiYMudjs2btHVxSC85H5IaO875IM7S0LiIgZmBN6w/GOFXK/NoERvUADKnd1a4/ParfAfkle9Jg4d6hDQ4LC59ijzZbiIxerZl2Iptpd1ydoK1apb0R6u9A7qf4=,iv:XOp+rhihpELSqPsGB57t7p6H3uXTJR5KJaerGpfzi9Q=,tag:iGZCFlBYdJXLnF99e4gp1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: litellm-env-secrets
stringData:
  LLM_API_KEY: ENC[AES256_GCM,data:f6Hh6V0=,iv:+cS4Ujt0KASZM3nFH4bN7oTSeagVOrhfj6ofJpn2BB4=,tag:108Iv6xLDONsiqiTa1dIqA==,type:str]
  LLM_MODEL: ENC[AES256_GCM,data:ipcLjOAkUS0dViwFrYKjpEo832zpTgQie8o2abkLqUnPn4xOYW4kXfo=,iv:C+D/k6hYbpxI4bUVMlY7cuvSSj2WvI3RHpRDP6OrTso=,tag:jEHm2qcGNMkNBELPldsaUQ==,type:str]
  LLM_BASE_URL: ENC[AES256_GCM,data:3VaDtILCwkYwIYYEKcAmqHacsb+AO4F6ZKTE,iv:Q1yrVTF+vvnQVSawHLCpm/CywxiFw8tpHYb9FyeAifo=,tag:BHzBKGqIn9I0+CY3XfSA4A==,type:str]
  LLM_TIMEOUT: ENC[AES256_GCM,data:XiaVpg==,iv:ePEK0h0QwfCIIkJ+9JUFIW4Hk10ei5cq9cYgZtOBdYY=,tag:GHDXaQdUjD/0aTSiyqAEog==,type:str]
  LLM_MAX_OUTPUT_TOKENS: ENC[AES256_GCM,data:Rm4T8aw=,iv:Elbhy4B6uJwxW1TpvyV9p66/9SXMf45nG+PNT6ONPT0=,tag:M5GsFRiWX/SThqw2HMmplQ==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGdoQ2J1QTFWUmE3Q0R5
        WXI5ZEhISHZkL1V6NXN1TnhYZG93bXNrS1VnCmx3eXpNUVdKajdTeHkwdGJXeGhN
        YnRFd1RMSXlSeWg5R0pCWUtGUDBoeFEKLS0tIFRGcnVTR2Y2VkdWMjdQYXAwbDVv
        ZTNPZmRUem9xYWFvcjlJL1owRmw1Z0kKdmz28FtkTsaD2p8uiwkXdNqmZSJXJcmW
        lpGowXY6aRVRpY/MGT0S5eLdCN2QGAe+pMV+XTbDt0hRvdZMcLHdhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T10:14:55Z"
  mac: ENC[AES256_GCM,data:AgriSc9pyc8Ue+Jz69S7P6DRrM3U10oVXO9+ap+IxjUeTe0RIiYMudjs2btHVxSC85H5IaO875IM7S0LiIgZmBN6w/GOFXK/NoERvUADKnd1a4/ParfAfkle9Jg4d6hDQ4LC59ijzZbiIxerZl2Iptpd1ydoK1apb0R6u9A7qf4=,iv:XOp+rhihpELSqPsGB57t7p6H3uXTJR5KJaerGpfzi9Q=,tag:iGZCFlBYdJXLnF99e4gp1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  # ‚áê must match imagePullSecrets entry
  name: ghcr-login-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:qAks+eFJvXLZDFVc9fc93qa1DaXCzh0UhT52itDtdhv18FTrzqgMCMAdpnOeDQ6Y9pB74OfD2hQBCE/eqzCRJLHQeI6rJZoe2fif7NeOMJg+LMQ5ASFO5Inc1iPEoXjQ/iat0wjVMZNXKo9UySxo3T7hrCctWU/iEGdL2P/mysz1C69512q1I/DFLh0OewkJunY0wqXkd7xMXIKZhBwKNr9kHp+efU7jS3WGHdVKyksSjx9US9TMCSWa+rBhzOhrHqpgUbbrnl0G+OCyRVmYtBcQCMfIakHsNWysWi2ypcSf2P5c+0whGBIlKbnSBOm8vrena7Qtv5A=,iv:EjzCf7FksRBbHq0/rwPmcsmEhb5QXi5xQzpeU+XLi8E=,tag:SnbFOIhCX8l5uQgg6XhHpQ==,type:str]
sops:
  age:
    - recipient: age1qs9scqdqfxvlqagc35m8vy427aczjt42l825q4l44et4nt7ed37qt6yrru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGdoQ2J1QTFWUmE3Q0R5
        WXI5ZEhISHZkL1V6NXN1TnhYZG93bXNrS1VnCmx3eXpNUVdKajdTeHkwdGJXeGhN
        YnRFd1RMSXlSeWg5R0pCWUtGUDBoeFEKLS0tIFRGcnVTR2Y2VkdWMjdQYXAwbDVv
        ZTNPZmRUem9xYWFvcjlJL1owRmw1Z0kKdmz28FtkTsaD2p8uiwkXdNqmZSJXJcmW
        lpGowXY6aRVRpY/MGT0S5eLdCN2QGAe+pMV+XTbDt0hRvdZMcLHdhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T10:14:55Z"
  mac: ENC[AES256_GCM,data:AgriSc9pyc8Ue+Jz69S7P6DRrM3U10oVXO9+ap+IxjUeTe0RIiYMudjs2btHVxSC85H5IaO875IM7S0LiIgZmBN6w/GOFXK/NoERvUADKnd1a4/ParfAfkle9Jg4d6hDQ4LC59ijzZbiIxerZl2Iptpd1ydoK1apb0R6u9A7qf4=,iv:XOp+rhihpELSqPsGB57t7p6H3uXTJR5KJaerGpfzi9Q=,tag:iGZCFlBYdJXLnF99e4gp1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
